### ISSUE TITLE
Broken reference to Tobi's scratch in IFS catalog

### ISSUE THREAD

**Issue by florianziemen** [nextGEMS/catalog#64]
IFS.IFS_9-FESOM_5-production.3D_hourly_healpix512 is broken because 
https://github.com/nextGEMS/catalog/blob/7e43a2bedd4b3f99eaaa9813bfe5ce886745ae21/IFS/tco1279-ng5-production-years.yaml#L99
references
/scratch/m/m300827/IFS_9-FESOM_5-production_3d_hourly_healpix512_combined.parq
which looks like it was cleaned out by the auto-deletion.

@d70-t @trackow

**Comment by trackow** [comment]
Thank you, Tobi had warned about this and we did not change it early enough.. 3D fields one can still access everything per decade. The all-decades-combined 3D catalog above Xabi will try to recover

**Comment by xabipedru** [comment]
The parquet has been re-created and placed in /work to avoid this problem happening again.
See https://github.com/nextGEMS/catalog/pull/65
